# Day 4 – Pandas Tasks
**Topics:** Import Pandas, load the student score dataset, explore rows, columns, and dataset information.

**Expected Outcome:** Dataset loaded successfully.

## 1. Import Pandas

In [8]:
import pandas as pd
import numpy as np

## 2. Load the Student Score Dataset
Loading the dataset from a CSV file (`student_scores.csv`) placed in the same folder as this notebook.

In [9]:
df = pd.read_csv("C:/Users/loq/Downloads/student_scores.csv")
print("Dataset loaded successfully!")

Dataset loaded successfully!

## 3. Explore Rows

In [10]:
# First 5 rows
df.head()

   StudentID   Name  Math  Science  English  Total  Percentage
0          1  Aarav    78       92       99    269       89.67
1          2   Isha    91       41       55    187       62.33
2          3  Rohan    68       63       54    185       61.67
3          4  Priya    54       83       86    223       74.33
4          5  Karan    82       69       90    241       80.33

In [11]:
# Last 5 rows
df.tail()

    StudentID   Name  Math  Science  English  Total  Percentage
15         16  Kavya    75       88       78    241       80.33
16         17  Manav    79       66       57    202       67.33
17         18   Riya    63       98       43    204       68.00
18         19   Yash    42       81       64    187       62.33
19         20  Tanvi    61       67       99    227       75.67

In [12]:
# Random sample of 5 rows
df.sample(5)

    StudentID   Name  Math  Science  English  Total  Percentage
9          10  Meera    58       72       42    172       57.33
11         12  Divya    50       97       90    237       79.00
17         18   Riya    63       98       43    204       68.00
12         13  Rahul    50       61       46    157       52.33
2           3  Rohan    68       63       54    185       61.67

## 4. Explore Columns

In [13]:
# List all column names
print("Columns:", list(df.columns))

Columns: ['StudentID', 'Name', 'Math', 'Science', 'English', 'Total', 'Percentage']

In [14]:
# Access a single column
df['Name']

0         Aarav
1          Isha
2         Rohan
3         Priya
4         Karan
5          Neha
6        Vikram
7         Sanya
8        Aditya
9         Meera
10        Arjun
11        Divya
12        Rahul
13        Pooja
14    Siddharth
15        Kavya
16        Manav
17         Riya
18         Yash
19        Tanvi
Name: Name, dtype: object

In [15]:
# Access multiple columns
df[['Name', 'Math', 'Science', 'English']]

         Name  Math  Science  English
0       Aarav    78       92       99
1        Isha    91       41       55
2       Rohan    68       63       54
3       Priya    54       83       86
4       Karan    82       69       90
5        Neha    47       77       83
6      Vikram    60       41       94
7       Sanya    78       99       91
8      Aditya    97       60       96
9       Meera    58       72       42
10      Arjun    62       51       76
11      Divya    50       97       90
12      Rahul    50       61       46
13      Pooja    63       83       60
14  Siddharth    92       64       48
15      Kavya    75       88       78
16      Manav    79       66       57
17       Riya    63       98       43
18       Yash    42       81       64
19      Tanvi    61       67       99

## 5. Dataset Information

In [16]:
# Shape of the dataset (rows, columns)
print("Shape:", df.shape)

Shape: (20, 7)

In [17]:
# Data types and non-null counts
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   20 non-null     int64
 1   Name        20 non-null     object
 2   Math        20 non-null     int64
 3   Science     20 non-null     int64
 4   English     20 non-null     int64
 5   Total       20 non-null     int64
 6   Percentage  20 non-null     float64
dtypes: float64(1), int64(5), object(1)
memory usage: 1.2+ KB

In [18]:
# Statistical summary of numeric columns
df.describe()

       StudentID       Math    Science    English       Total  Percentage
count   20.00000  20.000000  20.000000  20.000000   20.000000   20.000000
mean    10.50000  67.500000  72.650000  72.550000  212.700000   70.899000
std      5.91608  15.839657  17.574728  20.428244   31.136541   10.379029
min      1.00000  42.000000  41.000000  42.000000  157.000000   52.330000
25%      5.75000  57.000000  62.500000  54.750000  188.500000   62.832500
50%     10.50000  63.000000  70.500000  77.000000  205.000000   68.335000
75%     15.25000  78.250000  84.250000  90.250000  238.000000   79.332500
max     20.00000  97.000000  99.000000  99.000000  269.000000   89.670000

In [19]:
# Check for missing values
df.isnull().sum()

StudentID     0
Name          0
Math          0
Science       0
English       0
Total         0
Percentage    0
dtype: int64

In [20]:
# Check data types of each column
df.dtypes

StudentID       int64
Name           object
Math            int64
Science         int64
English         int64
Total           int64
Percentage    float64
dtype: object

## 6. Quick Insights

In [21]:
# Top scorer by Total marks
top_scorer = df.loc[df['Total'].idxmax()]
print("Top Scorer:\n", top_scorer)

Top Scorer:
 StudentID         1
Name          Aarav
Math             78
Science          92
English          99
Total           269
Percentage    89.67
Name: 0, dtype: object

In [22]:
# Average marks per subject
print("Average Math:", df['Math'].mean())
print("Average Science:", df['Science'].mean())
print("Average English:", df['English'].mean())

Average Math: 67.5
Average Science: 72.65
Average English: 72.55

In [23]:
# Students who scored above 80% percentage
df[df['Percentage'] > 80]

    StudentID    Name  Math  Science  English  Total  Percentage
0           1   Aarav    78       92       99    269       89.67
4           5   Karan    82       69       90    241       80.33
7           8   Sanya    78       99       91    268       89.33
8           9  Aditya    97       60       96    253       84.33
15         16   Kavya    75       88       78    241       80.33

## Summary
- Imported Pandas and loaded the student score dataset using `read_csv()`
- Explored rows using `head()`, `tail()`, and `sample()`
- Explored columns individually and in groups
- Checked dataset information using `shape`, `info()`, `describe()`, `isnull()`, and `dtypes`
- Derived quick insights (top scorer, subject averages, high performers)

**Day 4 Pandas fundamentals: completed.**