# Day 5 – Data Cleaning Tasks
**Topics:** Handle missing values, remove duplicates, and understand dataset statistics.

**Expected Outcome:** Clean dataset prepared.

## 1. Import Libraries & Load the Raw Dataset
We use `student_scores_raw.csv` — a version of the Day 4 dataset with some missing values and duplicate rows intentionally introduced, to practice cleaning.

In [18]:
import pandas as pd
import numpy as np

df = pd.read_csv("C:/Users/loq/Downloads/student_scores_raw.csv")
print("Dataset loaded successfully!")
df

Dataset loaded successfully!

    StudentID       Name  Math  Science  English  Total  Percentage
0           1      Aarav  78.0     92.0     99.0    269       89.67
1           2       Isha  91.0     41.0     55.0    187       62.33
2           3      Rohan   NaN     63.0     54.0    185       61.67
3           4      Priya  54.0     83.0     86.0    223       74.33
4           5      Karan  82.0     69.0     90.0    241       80.33
5           6       Neha  47.0      NaN     83.0    207       69.00
6           7     Vikram  60.0     41.0     94.0    195       65.00
7           8      Sanya  78.0     99.0     91.0    268       89.33
8           9     Aditya  97.0     60.0     96.0    253       84.33
9          10      Meera  58.0     72.0      NaN    172       57.33
10         11      Arjun  62.0     51.0     76.0    189       63.00
11         12      Divya  50.0     97.0     90.0    237       79.00
12         13      Rahul  50.0     61.0     46.0    157       52.33
13         14        NaN  63.0     83.0     60.0    206       68.67
14         15  Siddharth  92.0     64.0     48.0    204       68.00
15         16      Kavya  75.0     88.0     78.0    241       80.33
16         17      Manav  79.0     66.0     57.0    202       67.33
17         18       Riya  63.0     98.0     43.0    204       68.00
18         19       Yash  42.0     81.0     64.0    187       62.33
19         20      Tanvi  61.0     67.0     99.0    227       75.67
20          2       Isha  91.0     41.0     55.0    187       62.33
21          5      Karan  82.0     69.0     90.0    241       80.33

## 2. Understand Dataset Statistics (Before Cleaning)

In [19]:
# Shape of the dataset
print("Shape:", df.shape)

Shape: (22, 7)

In [20]:
# Dataset info (data types, non-null counts)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   22 non-null     int64
 1   Name        21 non-null     object
 2   Math        21 non-null     float64
 3   Science     21 non-null     float64
 4   English     21 non-null     float64
 5   Total       22 non-null     int64
 6   Percentage  22 non-null     float64
dtypes: float64(4), int64(2), object(1)
memory usage: 1.3+ KB

In [21]:
# Statistical summary
df.describe()

       StudentID       Math    Science    English       Total  Percentage
count  22.000000  21.000000  21.000000  21.000000   22.000000   22.000000
mean    9.863636  69.285714  70.761905  74.000000  212.818182   70.938182
std     6.010273  16.526170  18.425267  19.447365   30.768934   10.256469
min     1.000000  42.000000  41.000000  43.000000  157.000000   52.330000
25%     5.000000  58.000000  61.000000  55.000000  187.500000   62.497500
50%     9.500000  63.000000  69.000000  78.000000  205.000000   68.335000
75%    14.750000  82.000000  83.000000  90.000000  240.000000   79.997500
max    20.000000  97.000000  99.000000  99.000000  269.000000   89.670000

## 3. Handle Missing Values

In [22]:
# Check missing values per column
df.isnull().sum()

StudentID     0
Name          1
Math          1
Science       1
English       1
Total         0
Percentage    0
dtype: int64

In [23]:
# Percentage of missing values per column
(df.isnull().sum() / len(df)) * 100

StudentID     0.000000
Name          4.545455
Math          4.545455
Science       4.545455
English       4.545455
Total         0.000000
Percentage    0.000000
dtype: float64

In [24]:
# Rows containing missing values
df[df.isnull().any(axis=1)]

    StudentID   Name  Math  Science  English  Total  Percentage
2           3  Rohan   NaN     63.0     54.0    185       61.67
5           6   Neha  47.0      NaN     83.0    207       69.00
9          10  Meera  58.0     72.0      NaN    172       57.33
13         14    NaN  63.0     83.0     60.0    206       68.67

In [25]:
# Option 1: Fill missing numeric values with column mean
df['Math'] = df['Math'].fillna(df['Math'].mean())
df['Science'] = df['Science'].fillna(df['Science'].mean())
df['English'] = df['English'].fillna(df['English'].mean())

# Option 2: Fill missing categorical/text values with a placeholder
df['Name'] = df['Name'].fillna("Unknown")

print("Missing values after filling:\n", df.isnull().sum())

Missing values after filling:
 StudentID     0
Name          0
Math          0
Science       0
English       0
Total         0
Percentage    0
dtype: int64

## 4. Remove Duplicates

In [26]:
# Check number of duplicate rows
print("Duplicate rows before cleaning:", df.duplicated().sum())

Duplicate rows before cleaning: 2

In [27]:
# View the duplicate rows
df[df.duplicated()]

    StudentID   Name  Math  Science  English  Total  Percentage
20          2   Isha  91.0     41.0     55.0    187       62.33
21          5  Karan  82.0     69.0     90.0    241       80.33

In [28]:
# Drop duplicate rows
df = df.drop_duplicates().reset_index(drop=True)
print("Duplicate rows after cleaning:", df.duplicated().sum())
print("New shape:", df.shape)

Duplicate rows after cleaning: 0
New shape: (20, 7)

## 5. Recalculate Derived Columns
Since Math/Science/English values changed (missing values filled), recompute Total and Percentage for consistency.

In [29]:
df['Total'] = df['Math'] + df['Science'] + df['English']
df['Percentage'] = round(df['Total'] / 3, 2)
df.head()

   StudentID   Name       Math  Science  English       Total  Percentage
0          1  Aarav  78.000000     92.0     99.0  269.000000       89.67
1          2   Isha  91.000000     41.0     55.0  187.000000       62.33
2          3  Rohan  69.285714     63.0     54.0  186.285714       62.10
3          4  Priya  54.000000     83.0     86.0  223.000000       74.33
4          5  Karan  82.000000     69.0     90.0  241.000000       80.33

## 6. Dataset Statistics (After Cleaning)

In [30]:
# Confirm no missing values remain
print("Missing values:\n", df.isnull().sum())
print("\nDuplicate rows:", df.duplicated().sum())

Missing values:
 StudentID     0
Name          0
Math          0
Science       0
English       0
Total         0
Percentage    0
dtype: int64

Duplicate rows: 0

In [31]:
# Final statistical summary
df.describe()

       StudentID       Math    Science    English       Total  Percentage
count   20.00000  20.000000  20.000000  20.000000   20.000000   20.000000
mean    10.50000  67.564286  72.338095  74.150000  214.052381   71.350000
std      5.91608  15.844402  17.548799  19.120876   29.773950    9.924593
min      1.00000  42.000000  41.000000  43.000000  157.000000   52.330000
25%      5.75000  57.000000  62.500000  56.500000  193.500000   64.500000
50%     10.50000  63.000000  69.880952  77.000000  204.000000   68.000000
75%     15.25000  78.250000  84.250000  90.250000  238.000000   79.332500
max     20.00000  97.000000  99.000000  99.000000  269.000000   89.670000

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   20 non-null     int64
 1   Name        20 non-null     object
 2   Math        20 non-null     float64
 3   Science     20 non-null     float64
 4   English     20 non-null     float64
 5   Total       20 non-null     float64
 6   Percentage  20 non-null     float64
dtypes: float64(5), int64(1), object(1)
memory usage: 1.2+ KB

## 7. Save the Cleaned Dataset

In [33]:
df.to_csv("student_scores_clean.csv", index=False)
print("Clean dataset saved as student_scores_clean.csv")

Clean dataset saved as student_scores_clean.csv

## Summary
- Loaded a raw dataset containing missing values and duplicate rows
- Explored dataset statistics using `info()`, `describe()`, and `isnull().sum()`
- Handled missing values: filled numeric columns with mean, filled text column with a placeholder
- Identified and removed duplicate rows using `duplicated()` and `drop_duplicates()`
- Recalculated derived columns and verified the dataset was clean
- Saved the cleaned dataset to a new CSV file

**Day 5 Data Cleaning: completed — Clean dataset prepared.**